### ISSUE TITLE
$mixpanel.track - "Undefined is not a function" - Using minified version

### ISSUE THREAD

**Issue by nevcos** [kuhnza/angular-mixpanel#2]
Using "angular-mixpanel.min.js" version the following code gives me an "Undefined is not a function" exception:

```
this.$mixpanel.track(eventName, params, callback)
```

When using the "angular-mixpanel.js" file, there's no problem.

I think the minified version has some problem, the code is completely different.

**Comment by julienroubieu** [comment]
Same issue: the minified version did not track all events. No issue with the one from src.
It may be worth mentioning that I'm using Angular 1.3.

**Comment by kuhnza** [comment]
@nevcos is right, the minified version was out of date. Looks like I neglected to run a grunt build last time I updated the code base.

Would one of you mind retesting for me with the latest version (1.0.2)?

**Comment by nevcos** [comment]
Tnks @kuhnza, it's fixed! :+1:

**Comment by kuhnza** [comment]
Unreal, thanks @nevcos!
