### ISSUE TITLE
Add your library to a cdn

### ISSUE THREAD

**Issue by merenlin** [kuhnza/angular-mixpanel#4]
Hi, I would like to use your library in my project, although it would be good to have it on a public cdn. 
I'm trying to add it to cdnjs, your support would be appreciated:
https://github.com/cdnjs/cdnjs/pull/4198

**Comment by kuhnza** [comment]
Thanks @OxanaSachenkova. I can see that it's up there now, do I need to do anything from here to ensure new versions get published there?

**Comment by merenlin** [comment]
@kuhnza I believe it is going to autoupdate from now on, so as long as you use the same github repo, it should be just on cruise control

**Comment by kuhnza** [comment]
Thanks @OxanaSachenkova
